baseURL = "https://docs.restyled.io/"
title = "Restyled"
theme = "restyled"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[build]
  [build.resources]
    [build.resources.match]
      "assets/js/*.ts" = ["typescript"]
