baseURL = "https://restyledio.netlify.app/"
title = "Restyled"
theme = "restyled"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[build]
  [build.resources]
    [build.resources.match]
      "assets/js/*.ts" = ["typescript"]
