[build.environment]
HUGO_VERSION = "0.131.0"

[[edge_functions]]
  path = "/data-files/restylers/manifests/*"
  function = "manifests"

[[edge_functions]]
  path = "/restyler-tags"
  function = "restyler-tags"

[[redirects]]
  from = "/available-restylers"
  to = "https://github.com/restyled-io/restylers/blob/main/_docs/restylers.md"
  status = 301
  force = true

[[redirects]]
  from = "/restylers"
  to = "https://github.com/restyled-io/restylers/blob/main/_docs/restylers.md"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "https://github.com/restyled-io"
  status = 301
  force = true
