[build.environment]
HUGO_VERSION = "0.131.0"

[[edge_functions]]
  path = "/data-files/restylers/manifests/*"
  function = "manifests"

[[edge_functions]]
  path = "/restyler-tags"
  function = "restyler-tags"

[[redirects]]
  from = "/available-restylers"
  to = "/restylers"
  status = 301
  force = false
