name: Restyled

on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
      - synchronize

jobs:
  restyled:
    if: ${{ github.event.pull_request.merged != true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: restyled-io/actions/setup@v3
      - id: restyler
        uses: restyled-io/actions/run@v3
        with:
          fail-on-differences: true
      - if: ${{ !cancelled() }}
        uses: peter-evans/create-pull-request@v6
        with:
          base: ${{ steps.restyler.outputs.restyled-base }}
          branch: ${{ steps.restyler.outputs.restyled-head }}
          title: ${{ steps.restyler.outputs.restyled-title }}
          body: ${{ steps.restyler.outputs.restyled-body }}
